name: publish-images.yml

on:
  [workflow_dispatch]

jobs:

  build:
    permissions: write-all

    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/thegebirge/jndi-outcast

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build parent project with Maven
        working-directory: ./  # Run Maven from the parent directory
        run: mvn clean package

      - name: Build and push image for commons collections 6 servlet
        uses: docker/build-push-action@v5
        with:
          context: ./commons-collections-6
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/commons-collections-6:latest

      - name: Build and push image for tomcat 9 nashorn servlet
        uses: docker/build-push-action@v5
        with:
          context: ./tomcat-9-nashorn
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/tomcat-9-nashorn:latest

      - name: Build and push image for tomcat 10 nashorn servlet
        uses: docker/build-push-action@v5
        with:
          context: ./tomcat-10-nashorn
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/tomcat-10-nashorn:latest

      - name: Build and push image for tomcat 9 JShell servlet
        uses: docker/build-push-action@v5
        with:
          context: ./tomcat-9-jshell
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/tomcat-9-jshell:latest

      - name: Build and push image for tomcat 10 JShell servlet
        uses: docker/build-push-action@v5
        with:
          context: ./tomcat-10-jshell
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/tomcat-10-jshell:latest

      - name: Build and push image for h2 servlet
        uses: docker/build-push-action@v5
        with:
          context: ./h2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/h2:latest

      - name: Build and push image for groovy servlet
        uses: docker/build-push-action@v5
        with:
          context: ./groovy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO }}/groovy:latest